This is just for trying out some different method of adding trace to error messages
```
# ./err-test
00: err-test.c:32 in fun_a() - Bad wolf was here: yes
01: err-test.c:45 in fun_b()
```
